# -*- coding: utf-8 -*-
"""kadai1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2CaFS9mTpgBG8hmSMUKIy2cTtHCgA6_
"""

#課題１
print("課題１")

#1.
print("1.")
x = [0, 1, 2, 3, 4, 5, 6]
print(x[2])
print("")

#2.
print("2.")
l = len(x)
y = x.copy()
for i in range(0,l):
  y[i] = x[l-1-i]
  i += 1
print(y)
print("")


#3.
print("3.")
z = x[1:6:2]
print(z)
print("")


#4.
print("4.")
x = 10
if x > 0:
  print('x is positive')

def main():
    print("これはmain関数です")

if __name__ == "__main__":
    main()
